language:            node_js
node_js:
  - "lts/*"
  - "8"
env:
  - ENV=CI

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm run test

notifications:
  email:             false
